"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import ssl
from datetime import timedelta
from pathlib import Path

from django.conf import settings
from django.conf.urls.static import static
from dotenv import load_dotenv

urlpatterns = (
    [
        # suas rotas
    ]
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-u__rd#-8sa7^)h5j7%aqu17_^&ncgecyb&#z4(2me!_y#^xwun"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "eventos_session.authentication.CookieJWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
}

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "corsheaders",
    "guardian",
    "eventos_session",
    "api",
    "emails",
]

# APARENTIMENTE tem q ter isso, fé fml
AUTHENTICATION_BACKENDS = (
    "django.contrib.auth.backends.ModelBackend",
    "guardian.backends.ObjectPermissionBackend",
)

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "backend.urls"


MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")


TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.template.context_processors.i18n",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "pt-br"

TIME_ZONE = "America/Sao_Paulo"

USE_I18N = True

USE_TZ = True

# Caminho para arquivos de tradução
LOCALE_PATHS = [
    BASE_DIR / "locale",
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

AUTH_USER_MODEL = "eventos_session.Usuario"

BASE_SYSTEM_URL = "http://localhost:8000"
SYSTEM_ID = "4b055e06-b02a-4fc7-abe5-3d8d5dd81006"
API_KEY = "2e567c11e97215f381de0fe08e362743373ca4c67fd17c86bbdb57cc3dca088292"
JWT_SECRET_KEY = SECRET_KEY
JWT_ALGORITHM = "HS256"
JWT_ACCESS_TOKEN_EXPIRE_MINUTES = 30
JWT_REFRESH_TOKEN_EXPIRE_DAYS = 1

CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = True

# CONFIGURAÇÕES PARA ENVIO DE E-MAIL
# Envio de e-mail via SMTP
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# Autenticação do e-mail
EMAIL_HOST_USER = "sistema.eventos.testes@gmail.com"
EMAIL_HOST_PASSWORD = "eulnwpqkvvfwqbtn"

# Remetente padrão das mensagens
DEFAULT_FROM_EMAIL = "sistema.eventos.testes@gmail.com"

# CONFIGURAÇÕES DO CELERY E REDIS (Upstash) para envio de e-mails

# Connection String da UpStash
CELERY_BROKER_URL = "rediss://default:gQAAAAAAAfC-AAIgcDI2OTA0NjIzYTE2Njg0YjkxOTM5Y2YxMTkwMGNkYjQ1MQ@popular-falcon-127166.upstash.io:6379"

# SSL parâmetros de segurança
CELERY_BROKER_USE_SSL = {
    "ssl_cert_reqs": ssl.CERT_NONE  # Em produção deve ser configurado o Certificado e mudar a linha para: 'ssl_cert_reqs': ssl.CERT_REQUIRED
}

# Padrões de segurança e formato de dados para a fila
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE

# OTIMIZAÇÃO DE CONSUMO (UPSTASH / REDIS) => REMOVER NO FINAL ANTES DE IR PARA PRODUÇÃO INICIO
# Explicação: Essas opções ajuda a monitorar, mas estão consumindo muita taxa de envio no UpStash.
# Quando o projeto entrar em produção é interessante ligar essas opções para ajudar no monitoramento de e-mails.
CELERY_TASK_IGNORE_RESULT = True  # Ignorar o mensagens de resultado das tarefas
# Corta o envio de relatórios contínuos de status. (monitoramento)
CELERY_WORKER_SEND_TASK_EVENTS = False
CELERY_TASK_SEND_SENT_EVENT = False
CELERY_WORKER_ENABLE_REMOTE_CONTROL = False  # Evita a criação de caixas de correio virtuais e comandos de checagem (pings) para gerenciamento externo.
# OTIMIZAÇÃO DE CONSUMO (UPSTASH / REDIS) => REMOVER NO FINAL ANTES DE IR PARA PRODUÇÃO FIM
